project:
  title: "Python Programming (CS2023)"
  output-dir: docs/_build/html/slides
  render:
    - "*.qmd"
resources:
  - "data/*"
format: 
  revealjs:
    slide-level: 4
    toc-depth: 4
    scrollable: true
    preview-links: true
    css: "docs/_static/quarto-styles.css"
    controls: true
