project:
  title: "Python Programming (CS2023)"
  output-dir: docs/_build/html/slides
resources:
  - "docs/_static/*"
format: 
  revealjs:
    slide-level: 3
    scrollable: true
    preview-links: true
    css: "quarto-styles.css"
    controls: true
