# Matplotlib


## What is Matplotlib?

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It provides the tools and framework for building a wide variety of plots and charts.


## Reference Documentation {.hide .smaller-80}

The following resources from the official Matplotlib documentation provide additional information on the library:

- [Matplotlib Homepage](https://matplotlib.org/)
- [Matplotlib Documentation](https://matplotlib.org/stable/contents.html)

## Installing {.hide}

Matplotlib is a third-party library, so you need to install it separately. You can install it using `pip`:

```bash
pip install matplotlib
```

Or if using `conda`:

```bash
conda install matplotlib
```

## Rendering in Different Environments {.hide .smaller-85}

Matplotlib can render plots in various environments. Sometimes, it may assume a GUI is available when it is not. To avoid issues on systems without a display, set the backend to `Agg`. This non-interactive backend is ideal for generating plots as image files or for batch processing. 

You can set the backend with:

```python
import matplotlib
matplotlib.use('Agg')  # Use 'Agg' for non-GUI environments
```


