name: deploy-book

# Run this when the master or main branch changes
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - docs/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    # Setup Python and install dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build docs/

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_build/html"

    # # Deploy the book's HTML to GitHub Pages
    # - name: Deploy to GitHub Pages
    #   id: deployment
    #   uses: actions/deploy-pages@v4
    #   with:
    #     branch: main   # The branch you want to deploy to
    #     repository: 20CS2023-FS24/20CS2023-FS24.github.io  # Specify the repository in the format owner/repo
    #     folder: _build/html  # The folder that you want to deploy
    #     clean: true
    #     token: ${{ secrets.GITHUB_TOKEN }}  # This is the GitHub secret token
